


                /* ======================================= *
                 *              I N C L U D E              *
                 * ======================================= */

#include "bsp.h"

                /* ======================================= *
                 *            C O N S T A N T S            *
                 * ======================================= */

/*!
 * ASCII character table for the LCD.
 */
const SEGMENT_VARIABLE(ascii_table5x7[][5], U8, SEG_CODE) =
{
	{0x00, 0x00, 0x00, 0x00, 0x00},// (space)
	{0x00, 0x00, 0x5F, 0x00, 0x00},// !
	{0x00, 0x07, 0x00, 0x07, 0x00},// "
	{0x14, 0x7F, 0x14, 0x7F, 0x14},// #
	{0x24, 0x2A, 0x7F, 0x2A, 0x12},// $
	{0x23, 0x13, 0x08, 0x64, 0x62},// %
	{0x36, 0x49, 0x55, 0x22, 0x50},// &
	{0x00, 0x05, 0x03, 0x00, 0x00},// '
	{0x00, 0x1C, 0x22, 0x41, 0x00},// (
	{0x00, 0x41, 0x22, 0x1C, 0x00},// )
	{0x08, 0x2A, 0x1C, 0x2A, 0x08},// *
	{0x08, 0x08, 0x3E, 0x08, 0x08},// +
	{0x00, 0x50, 0x30, 0x00, 0x00},// ,
	{0x08, 0x08, 0x08, 0x08, 0x08},// -
	{0x00, 0x60, 0x60, 0x00, 0x00},// .
	{0x20, 0x10, 0x08, 0x04, 0x02},// /
	{0x3E, 0x51, 0x49, 0x45, 0x3E},// 0
	{0x00, 0x42, 0x7F, 0x40, 0x00},// 1
	{0x42, 0x61, 0x51, 0x49, 0x46},// 2
	{0x21, 0x41, 0x45, 0x4B, 0x31},// 3
	{0x18, 0x14, 0x12, 0x7F, 0x10},// 4
	{0x27, 0x45, 0x45, 0x45, 0x39},// 5
	{0x3C, 0x4A, 0x49, 0x49, 0x30},// 6
	{0x01, 0x71, 0x09, 0x05, 0x03},// 7
	{0x36, 0x49, 0x49, 0x49, 0x36},// 8
	{0x06, 0x49, 0x49, 0x29, 0x1E},// 9
	{0x00, 0x36, 0x36, 0x00, 0x00},// :
	{0x00, 0x56, 0x36, 0x00, 0x00},// ;
	{0x00, 0x08, 0x14, 0x22, 0x41},// <
	{0x14, 0x14, 0x14, 0x14, 0x14},// =
	{0x41, 0x22, 0x14, 0x08, 0x00},// >
	{0x02, 0x01, 0x51, 0x09, 0x06},// ?
	{0x32, 0x49, 0x79, 0x41, 0x3E},// @
	{0x7E, 0x11, 0x11, 0x11, 0x7E},// A
	{0x7F, 0x49, 0x49, 0x49, 0x36},// B
	{0x3E, 0x41, 0x41, 0x41, 0x22},// C
	{0x7F, 0x41, 0x41, 0x22, 0x1C},// D
	{0x7F, 0x49, 0x49, 0x49, 0x41},// E
	{0x7F, 0x09, 0x09, 0x01, 0x01},// F
	{0x3E, 0x41, 0x41, 0x51, 0x32},// G
	{0x7F, 0x08, 0x08, 0x08, 0x7F},// H
	{0x00, 0x41, 0x7F, 0x41, 0x00},// I
	{0x20, 0x40, 0x41, 0x3F, 0x01},// J
	{0x7F, 0x08, 0x14, 0x22, 0x41},// K
	{0x7F, 0x40, 0x40, 0x40, 0x40},// L
	{0x7F, 0x02, 0x04, 0x02, 0x7F},// M
	{0x7F, 0x04, 0x08, 0x10, 0x7F},// N
	{0x3E, 0x41, 0x41, 0x41, 0x3E},// O
	{0x7F, 0x09, 0x09, 0x09, 0x06},// P
	{0x3E, 0x41, 0x51, 0x21, 0x5E},// Q
	{0x7F, 0x09, 0x19, 0x29, 0x46},// R
	{0x46, 0x49, 0x49, 0x49, 0x31},// S
	{0x01, 0x01, 0x7F, 0x01, 0x01},// T
	{0x3F, 0x40, 0x40, 0x40, 0x3F},// U
	{0x1F, 0x20, 0x40, 0x20, 0x1F},// V
	{0x7F, 0x20, 0x18, 0x20, 0x7F},// W
	{0x63, 0x14, 0x08, 0x14, 0x63},// X
	{0x03, 0x04, 0x78, 0x04, 0x03},// Y
	{0x61, 0x51, 0x49, 0x45, 0x43},// Z
	{0x00, 0x00, 0x7F, 0x41, 0x41},// [
	{0x02, 0x04, 0x08, 0x10, 0x20},// "\"
	{0x41, 0x41, 0x7F, 0x00, 0x00},// ]
	{0x04, 0x02, 0x01, 0x02, 0x04},// ^
	{0x40, 0x40, 0x40, 0x40, 0x40},// _
	{0x00, 0x01, 0x02, 0x04, 0x00},// `
	{0x20, 0x54, 0x54, 0x54, 0x78},// a
	{0x7F, 0x48, 0x44, 0x44, 0x38},// b
	{0x38, 0x44, 0x44, 0x44, 0x20},// c
	{0x38, 0x44, 0x44, 0x48, 0x7F},// d
	{0x38, 0x54, 0x54, 0x54, 0x18},// e
	{0x08, 0x7E, 0x09, 0x01, 0x02},// f
	{0x08, 0x14, 0x54, 0x54, 0x3C},// g
	{0x7F, 0x08, 0x04, 0x04, 0x78},// h
	{0x00, 0x44, 0x7D, 0x40, 0x00},// i
	{0x20, 0x40, 0x44, 0x3D, 0x00},// j
	{0x00, 0x7F, 0x10, 0x28, 0x44},// k
	{0x00, 0x41, 0x7F, 0x40, 0x00},// l
	{0x7C, 0x04, 0x18, 0x04, 0x78},// m
	{0x7C, 0x08, 0x04, 0x04, 0x78},// n
	{0x38, 0x44, 0x44, 0x44, 0x38},// o
	{0x7C, 0x14, 0x14, 0x14, 0x08},// p
	{0x08, 0x14, 0x14, 0x18, 0x7C},// q
	{0x7C, 0x08, 0x04, 0x04, 0x08},// r
	{0x48, 0x54, 0x54, 0x54, 0x20},// s
	{0x04, 0x3F, 0x44, 0x40, 0x20},// t
	{0x3C, 0x40, 0x40, 0x20, 0x7C},// u
	{0x1C, 0x20, 0x40, 0x20, 0x1C},// v
	{0x3C, 0x40, 0x30, 0x40, 0x3C},// w
	{0x44, 0x28, 0x10, 0x28, 0x44},// x
	{0x0C, 0x50, 0x50, 0x50, 0x3C},// y
	{0x44, 0x64, 0x54, 0x4C, 0x44},// z
	{0x00, 0x08, 0x36, 0x41, 0x00},// {
	{0x00, 0x00, 0x7F, 0x00, 0x00},// |
	{0x00, 0x41, 0x36, 0x08, 0x00},// }
	{0x08, 0x08, 0x2A, 0x1C, 0x08},// ->
	{0x00, 0x00, 0x07, 0x07, 0x07} // fok
};


/** NOTE: the picture description arrays are generated by Fntcvtr.exe
 **       The first element of the array should be number of the vertical pixels / 8.
 **       The second element of the array should be the number of horizontal pixels.
 **/

/*!
 * ALERT ICON
 * horizontal size is 128 pixels.
 * vertical size is 32 pixels.
 */
const SEGMENT_VARIABLE(alert128x32[], U8, SEG_CODE) =
{
    4,128,
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\xf8','\xff','\xff','\x19',
    '\xf8','\xff','\xff','\x19',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\xf8','\xff','\xff','\x19',
    '\xf8','\xff','\xff','\x19',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\xff','\xff','\x1f',
    '\x80','\xff','\xff','\x1f',
    '\xc0','\x00','\x03','\x00',
    '\x60','\x00','\x03','\x00',
    '\x30','\x00','\x03','\x00',
    '\x18','\x00','\x03','\x00',
    '\x18','\x00','\x03','\x00',
    '\x18','\x00','\x03','\x00',
    '\x18','\x00','\x03','\x00',
    '\x30','\x00','\x03','\x00',
    '\x60','\x00','\x03','\x00',
    '\xc0','\x00','\x03','\x00',
    '\x80','\xff','\xff','\x1f',
    '\x00','\xff','\xff','\x1f',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\xf8','\xff','\xff','\x1f',
    '\xf8','\xff','\xff','\x1f',
    '\x00','\x00','\x00','\x18',
    '\x00','\x00','\x00','\x18',
    '\x00','\x00','\x00','\x18',
    '\x00','\x00','\x00','\x18',
    '\x00','\x00','\x00','\x18',
    '\x00','\x00','\x00','\x18',
    '\x00','\x00','\x00','\x18',
    '\x00','\x00','\x00','\x18',
    '\x00','\x00','\x00','\x18',
    '\x00','\x00','\x00','\x18',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\xf8','\xff','\xff','\x1f',
    '\xf8','\xff','\xff','\x1f',
    '\x18','\x60','\x00','\x18',
    '\x18','\x60','\x00','\x18',
    '\x18','\x60','\x00','\x18',
    '\x18','\x60','\x00','\x18',
    '\x18','\x60','\x00','\x18',
    '\x18','\x60','\x00','\x18',
    '\x18','\x60','\x00','\x18',
    '\x18','\x60','\x00','\x18',
    '\x18','\x00','\x00','\x18',
    '\x18','\x00','\x00','\x18',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\xf8','\xff','\xff','\x1f',
    '\xf8','\xff','\xff','\x1f',
    '\x18','\xc0','\x00','\x00',
    '\x18','\xc0','\x00','\x00',
    '\x18','\xc0','\x00','\x00',
    '\x18','\xc0','\x00','\x00',
    '\x18','\xc0','\x00','\x00',
    '\x18','\xc0','\x00','\x00',
    '\x18','\xc0','\x00','\x00',
    '\x18','\xc0','\x00','\x00',
    '\x18','\xc0','\x00','\x00',
    '\x18','\xc0','\x00','\x00',
    '\x18','\xc0','\x00','\x00',
    '\xf0','\x7f','\xff','\x1f',
    '\xe0','\x3f','\xfe','\x1f',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x18','\x00','\x00','\x00',
    '\x18','\x00','\x00','\x00',
    '\x18','\x00','\x00','\x00',
    '\x18','\x00','\x00','\x00',
    '\x18','\x00','\x00','\x00',
    '\x18','\x00','\x00','\x00',
    '\x18','\x00','\x00','\x00',
    '\xf8','\xff','\xff','\x1f',
    '\xf8','\xff','\xff','\x1f',
    '\x18','\x00','\x00','\x00',
    '\x18','\x00','\x00','\x00',
    '\x18','\x00','\x00','\x00',
    '\x18','\x00','\x00','\x00',
    '\x18','\x00','\x00','\x00',
    '\x18','\x00','\x00','\x00',
    '\x18','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\xf8','\xff','\xff','\x19',
    '\xf8','\xff','\xff','\x19',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\xf8','\xff','\xff','\x19',
    '\xf8','\xff','\xff','\x19',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00',
    '\x00','\x00','\x00','\x00'
};

/*!
 * INVERTED ALERT ICON
 * horizontal size is 128 pixels.
 * vertical size is 32 pixels.
 */
const SEGMENT_VARIABLE(alert_inverted128x32[], U8, SEG_CODE) =
{
    4,128,
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\x07','\x00','\x00','\xe6',
    '\x07','\x00','\x00','\xe6',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\x07','\x00','\x00','\xe6',
    '\x07','\x00','\x00','\xe6',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\x00','\x00','\xe0',
    '\x7f','\x00','\x00','\xe0',
    '\x3f','\xff','\xfc','\xff',
    '\x9f','\xff','\xfc','\xff',
    '\xcf','\xff','\xfc','\xff',
    '\xe7','\xff','\xfc','\xff',
    '\xe7','\xff','\xfc','\xff',
    '\xe7','\xff','\xfc','\xff',
    '\xe7','\xff','\xfc','\xff',
    '\xcf','\xff','\xfc','\xff',
    '\x9f','\xff','\xfc','\xff',
    '\x3f','\xff','\xfc','\xff',
    '\x7f','\x00','\x00','\xe0',
    '\xff','\x00','\x00','\xe0',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\x07','\x00','\x00','\xe0',
    '\x07','\x00','\x00','\xe0',
    '\xff','\xff','\xff','\xe7',
    '\xff','\xff','\xff','\xe7',
    '\xff','\xff','\xff','\xe7',
    '\xff','\xff','\xff','\xe7',
    '\xff','\xff','\xff','\xe7',
    '\xff','\xff','\xff','\xe7',
    '\xff','\xff','\xff','\xe7',
    '\xff','\xff','\xff','\xe7',
    '\xff','\xff','\xff','\xe7',
    '\xff','\xff','\xff','\xe7',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\x07','\x00','\x00','\xe0',
    '\x07','\x00','\x00','\xe0',
    '\xe7','\x9f','\xff','\xe7',
    '\xe7','\x9f','\xff','\xe7',
    '\xe7','\x9f','\xff','\xe7',
    '\xe7','\x9f','\xff','\xe7',
    '\xe7','\x9f','\xff','\xe7',
    '\xe7','\x9f','\xff','\xe7',
    '\xe7','\x9f','\xff','\xe7',
    '\xe7','\x9f','\xff','\xe7',
    '\xe7','\xff','\xff','\xe7',
    '\xe7','\xff','\xff','\xe7',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\x07','\x00','\x00','\xe0',
    '\x07','\x00','\x00','\xe0',
    '\xe7','\x3f','\xff','\xff',
    '\xe7','\x3f','\xff','\xff',
    '\xe7','\x3f','\xff','\xff',
    '\xe7','\x3f','\xff','\xff',
    '\xe7','\x3f','\xff','\xff',
    '\xe7','\x3f','\xff','\xff',
    '\xe7','\x3f','\xff','\xff',
    '\xe7','\x3f','\xff','\xff',
    '\xe7','\x3f','\xff','\xff',
    '\xe7','\x3f','\xff','\xff',
    '\xe7','\x3f','\xff','\xff',
    '\x0f','\x80','\x00','\xe0',
    '\x1f','\xc0','\x01','\xe0',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xe7','\xff','\xff','\xff',
    '\xe7','\xff','\xff','\xff',
    '\xe7','\xff','\xff','\xff',
    '\xe7','\xff','\xff','\xff',
    '\xe7','\xff','\xff','\xff',
    '\xe7','\xff','\xff','\xff',
    '\xe7','\xff','\xff','\xff',
    '\x07','\x00','\x00','\xe0',
    '\x07','\x00','\x00','\xe0',
    '\xe7','\xff','\xff','\xff',
    '\xe7','\xff','\xff','\xff',
    '\xe7','\xff','\xff','\xff',
    '\xe7','\xff','\xff','\xff',
    '\xe7','\xff','\xff','\xff',
    '\xe7','\xff','\xff','\xff',
    '\xe7','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\x07','\x00','\x00','\xe6',
    '\x07','\x00','\x00','\xe6',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\x07','\x00','\x00','\xe6',
    '\x07','\x00','\x00','\xe6',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff',
    '\xff','\xff','\xff','\xff'
};

/*!
 * UN-ARM ICON
 * horizontal size is 34 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(unarm_inverted34x8[], U8, SEG_CODE) =
{
    1,34,
    '\xff',
    '\xc1',
    '\xbf',
    '\xbf',
    '\xbf',
    '\x81',
    '\xff',
    '\x81',
    '\xf7',
    '\xef',
    '\xdf',
    '\x81',
    '\xff',
    '\xf7',
    '\xf7',
    '\xf7',
    '\xff',
    '\x83',
    '\xed',
    '\xed',
    '\xed',
    '\x83',
    '\xff',
    '\x81',
    '\xed',
    '\xed',
    '\x93',
    '\xff',
    '\x81',
    '\xfb',
    '\xf7',
    '\xfb',
    '\x81',
    '\xff'
};

/*!
 * STATUS ICON
 * horizontal size is 37 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(status_inverted37x8[], U8, SEG_CODE) =
{
    1,37,
    '\xff',
    '\xbb',
    '\xb5',
    '\xb5',
    '\xb5',
    '\xcd',
    '\xff',
    '\xfd',
    '\xfd',
    '\x81',
    '\xfd',
    '\xfd',
    '\xff',
    '\x83',
    '\xed',
    '\xed',
    '\xed',
    '\x83',
    '\xff',
    '\xfd',
    '\xfd',
    '\x81',
    '\xfd',
    '\xfd',
    '\xff',
    '\xc1',
    '\xbf',
    '\xbf',
    '\xbf',
    '\x81',
    '\xff',
    '\xbb',
    '\xb5',
    '\xb5',
    '\xb5',
    '\xcd',
    '\xff'
};

/*!
 * ARM ICON
 * horizontal size is 18 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(arm_inverted18x8[], U8, SEG_CODE) =
{
    1,18,
    '\xff',
    '\x83',
    '\xed',
    '\xed',
    '\xed',
    '\x83',
    '\xff',
    '\x81',
    '\xed',
    '\xed',
    '\x93',
    '\xff',
    '\x81',
    '\xfb',
    '\xf7',
    '\xfb',
    '\x81',
    '\xff'
};

/*!
 * CANCEL ICON
 * horizontal size is 33 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(cancel_inverted33x8[], U8, SEG_CODE) =
{
    1,33,
    '\xff',
    '\xc3',
    '\xbd',
    '\xbd',
    '\xbd',
    '\xff',
    '\x83',
    '\xed',
    '\xed',
    '\xed',
    '\x83',
    '\xff',
    '\x81',
    '\xf7',
    '\xef',
    '\xdf',
    '\x81',
    '\xff',
    '\xc3',
    '\xbd',
    '\xbd',
    '\xbd',
    '\xff',
    '\x81',
    '\xb5',
    '\xb5',
    '\xbd',
    '\xff',
    '\x81',
    '\xbf',
    '\xbf',
    '\xbf',
    '\xff'
};

/*!
 * ALERT ICON
 * horizontal size is 8 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(al_inverted8x8[], U8, SEG_CODE) =
{
    1,8,
    '\xff',
    '\xff',
    '\xff',
    '\xa1',
    '\xa1',
    '\xff',
    '\xff',
    '\xff'
};

/*!
 * UP ICON
 * horizontal size is 16 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(up_inverted16x8[], U8, SEG_CODE) =
{
    1,16,
    '\xff',
    '\xff',
    '\xff',
    '\xff',
    '\xef',
    '\xe7',
    '\xe3',
    '\x81',
    '\x81',
    '\xe3',
    '\xe7',
    '\xef',
    '\xff',
    '\xff',
    '\xff',
    '\xff'
};

/*!
 * DOWN ICON
 * horizontal size is 16 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(down_inverted16x8[], U8, SEG_CODE) =
{
    1,16,
    '\xff',
    '\xff',
    '\xff',
    '\xff',
    '\xf7',
    '\xe7',
    '\xc7',
    '\x81',
    '\x81',
    '\xc7',
    '\xe7',
    '\xf7',
    '\xff',
    '\xff',
    '\xff',
    '\xff'
};

/*!
 * UP_DOWN ICON
 * horizontal size is 16 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(up_down_inverted16x8[], U8, SEG_CODE) =
{
    1,16,
    '\xff',
    '\xff',
    '\xf7',
    '\xf3',
    '\x81',
    '\xf3',
    '\xf7',
    '\xff',
    '\xff',
    '\xef',
    '\xcf',
    '\x81',
    '\xcf',
    '\xef',
    '\xff',
    '\xff'
};

/*!
 * MINUS ICON
 * horizontal size is 16 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(minus_inverted16x8[], U8, SEG_CODE) =
{
    1,16,
    '\xff',
    '\xff',
    '\xff',
    '\xff',
    '\xff',
    '\xe7',
    '\xe7',
    '\xe7',
    '\xe7',
    '\xe7',
    '\xe7',
    '\xff',
    '\xff',
    '\xff',
    '\xff',
    '\xff'
};

/*!
 * PLUS ICON
 * horizontal size is 16 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(plus_inverted16x8[], U8, SEG_CODE) =
{
    1,16,
    '\xff',
    '\xff',
    '\xff',
    '\xff',
    '\xff',
    '\xe7',
    '\xe7',
    '\x81',
    '\x81',
    '\xe7',
    '\xe7',
    '\xff',
    '\xff',
    '\xff',
    '\xff',
    '\xff'
};

/*!
 * INFO ICON
 * horizontal size is 21 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(info_inverted21x8[], U8, SEG_CODE) =
{
    1,21,
    '\xff',
    '\x81',
    '\xff',
    '\x81',
    '\xfb',
    '\xf7',
    '\xef',
    '\xdf',
    '\x81',
    '\xff',
    '\x81',
    '\xf5',
    '\xf5',
    '\xfd',
    '\xff',
    '\xc3',
    '\xbd',
    '\xbd',
    '\xbd',
    '\xc3',
    '\xff'
};

/*!
 * ADV. MENU ICON
 * horizontal size is 41 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(adv_menu_inverted41x8[], U8, SEG_CODE) =
{
    1,41,
    '\xff',
    '\x83',
    '\xed',
    '\xed',
    '\x83',
    '\xff',
    '\x81',
    '\xbd',
    '\xbd',
    '\xc3',
    '\xff',
    '\xe1',
    '\xdf',
    '\xbf',
    '\xdf',
    '\xe1',
    '\xbf',
    '\xff',
    '\xff',
    '\xff',
    '\x81',
    '\xfb',
    '\xf7',
    '\xfb',
    '\x81',
    '\xff',
    '\xc3',
    '\xbd',
    '\xbd',
    '\xc3',
    '\xff',
    '\x81',
    '\xbd',
    '\xbd',
    '\xc3',
    '\xff',
    '\x81',
    '\xb5',
    '\xb5',
    '\xbd',
    '\xff'
};

/*!
 * GO ICON
 * horizontal size is 16 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(go_inverted16x8[], U8, SEG_CODE) =
{
    1,16,
    '\xff',
    '\xff',
    '\xc3',
    '\xbd',
    '\xbd',
    '\xad',
    '\xcf',
    '\xff',
    '\xff',
    '\xc3',
    '\xbd',
    '\xbd',
    '\xbd',
    '\xc3',
    '\xff',
    '\xff'
};

/*!
 * ANT for SALVE1 ICON
 * horizontal size is 11 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(ant_slave1_11x8[], U8, SEG_CODE) =
{
    1,11,
    '\x01',
    '\x02',
    '\x04',
    '\x7f',
    '\x04',
    '\x02',
    '\x01',
    '\x08',
    '\x7c',
    '\x00',
    '\x22'
};

/*!
 * ANT for SALVE2 ICON
 * horizontal size is 13 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(ant_slave2_13x8[], U8, SEG_CODE) =
{
    1,13,
    '\x01',
    '\x02',
    '\x04',
    '\x7f',
    '\x04',
    '\x02',
    '\x01',
    '\x48',
    '\x64',
    '\x54',
    '\x48',
    '\x00',
    '\x22'
};

/*!
 * ANT for SALVE3 ICON
 * horizontal size is 13 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(ant_slave3_13x8[], U8, SEG_CODE) =
{
    1,13,
    '\x01',
    '\x02',
    '\x04',
    '\x7f',
    '\x04',
    '\x02',
    '\x01',
    '\x28',
    '\x44',
    '\x54',
    '\x28',
    '\x00',
    '\x22'
};

/*!
 * ANT for SALVE4 ICON
 * horizontal size is 13 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(ant_slave4_13x8[], U8, SEG_CODE) =
{
    1,13,
    '\x01',
    '\x02',
    '\x04',
    '\x7f',
    '\x04',
    '\x02',
    '\x21',
    '\x30',
    '\x28',
    '\x7c',
    '\x20',
    '\x00',
    '\x22'
};


/*!
 * LED OFF ICON
 * horizontal size is 8 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(led_off_8x8[], U8, SEG_CODE) =
{
    1,8,
    '\x18',
    '\x66',
    '\x42',
    '\x81',
    '\x81',
    '\x42',
    '\x66',
    '\x18'
};

/*!
 * LED ON ICON
 * horizontal size is 8 pixels
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(led_on_8x8[], U8, SEG_CODE) =
{
    1,8,
    '\x18',
    '\x7e',
    '\x7e',
    '\xff',
    '\xff',
    '\x7e',
    '\x7e',
    '\x18'
};

/*!
 * RSSI clear
 * horizontal size is 14 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(rssi_clear_14x8[], U8, SEG_CODE) =
{
    1,14,
    '\x00',
    '\x00',
    '\x00',
    '\x00',
    '\x00',
    '\x00',
    '\x00',
    '\x00',
    '\x00',
    '\x00',
    '\x00',
    '\x00',
    '\x00',
    '\x00'
};

/*!
 * RSSI1 ICON
 * horizontal size is 2 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(rssi12x8[], U8, SEG_CODE) =
{
    1,2,
    '\x40',
    '\x40'
};

/*!
 * RSSI2 ICON
 * horizontal size is 4 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(rssi24x8[], U8, SEG_CODE) =
{
    1,4,
    '\x40',
    '\x40',
    '\x60',
    '\x60'
};

/*!
 * RSSI3 ICON
 * horizontal size is 6 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(rssi36x8[], U8, SEG_CODE) =
{
    1,6,
    '\x40',
    '\x40',
    '\x60',
    '\x60',
    '\x70',
    '\x70'
};

/*!
 * RSSI4 ICON
 * horizontal size is 8 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(rssi48x8[], U8, SEG_CODE) =
{
    1,8,
    '\x40',
    '\x40',
    '\x60',
    '\x60',
    '\x70',
    '\x70',
    '\x78',
    '\x78'
};

/*!
 * RSSI5 ICON
 * horizontal size is 10 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(rssi510x8[], U8, SEG_CODE) =
{
    1,10,
    '\x40',
    '\x40',
    '\x60',
    '\x60',
    '\x70',
    '\x70',
    '\x78',
    '\x78',
    '\x7c',
    '\x7c'
};

/*!
 * RSSI6 ICON
 * horizontal size is 12 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(rssi612x8[], U8, SEG_CODE) =
{
    1,12,
    '\x40',
    '\x40',
    '\x60',
    '\x60',
    '\x70',
    '\x70',
    '\x78',
    '\x78',
    '\x7c',
    '\x7c',
    '\x7e',
    '\x7e'
};

/*!
 * RSSI7 ICON
 * horizontal size is 14 pixels.
 * vertical size is 8 pixels.
 */
const SEGMENT_VARIABLE(rssi714x8[], U8, SEG_CODE) =
{
    1,14,
    '\x40',
    '\x40',
    '\x60',
    '\x60',
    '\x70',
    '\x70',
    '\x78',
    '\x78',
    '\x7c',
    '\x7c',
    '\x7e',
    '\x7e',
    '\x7f',
    '\x7f'
};

/*!
 * SILABS LOGO
 * horizontal size is 87 pixels.
 * vertical size is 40 pixels.
 */
const SEGMENT_VARIABLE(silabs87x40[], U8, SEG_CODE) =
{
    5,87,
    '\x00','\x00','\x00','\xc0','\x61',
    '\x00','\x00','\x00','\x60','\xc2',
    '\x00','\x00','\x00','\x60','\xc4',
    '\x00','\x00','\x00','\xc0','\x78',
    '\x00','\x00','\x3e','\x00','\x00',
    '\x00','\x80','\x7f','\x00','\x00',
    '\x00','\xc0','\xff','\x00','\x00',
    '\x00','\xe0','\xff','\x01','\x00',
    '\x00','\xf0','\xff','\x03','\x00',
    '\x00','\xf8','\xff','\xe7','\xff',
    '\x00','\xf8','\xff','\x07','\x00',
    '\x00','\xfc','\xff','\x0f','\x00',
    '\x00','\xfe','\xff','\x0d','\x00',
    '\x00','\xfe','\x7f','\x08','\x00',
    '\x00','\xff','\x3f','\x08','\x00',
    '\x00','\xff','\x3f','\xe0','\xff',
    '\x80','\xff','\x1f','\x00','\x80',
    '\x80','\xff','\x1f','\x00','\x80',
    '\xc0','\xc7','\x0f','\x00','\x80',
    '\xc0','\x83','\x0f','\x00','\x00',
    '\xe0','\x01','\x0f','\x00','\x00',
    '\xe0','\x00','\x0f','\x00','\x00',
    '\xe0','\x00','\x0f','\x00','\x00',
    '\x70','\x00','\x0f','\xe0','\xff',
    '\x70','\x00','\xce','\x00','\x00',
    '\x30','\x00','\xee','\x01','\x00',
    '\x38','\x00','\xfe','\x01','\x00',
    '\x18','\x00','\xfe','\x03','\x00',
    '\x18','\x00','\xfe','\x03','\x00',
    '\x18','\x00','\xfc','\xc3','\x7f',
    '\x0c','\x00','\xfc','\x63','\xc0',
    '\x0c','\x00','\xfc','\x67','\xc0',
    '\x0c','\x00','\xfc','\xc7','\x60',
    '\x06','\x0e','\xfc','\x07','\x00',
    '\x06','\x1f','\xfc','\x07','\x00',
    '\x86','\x3f','\xfc','\x07','\x00',
    '\xc2','\x3f','\xfc','\x07','\x00',
    '\xc2','\x7f','\xfc','\xc7','\x7f',
    '\xe3','\x6f','\xfc','\x67','\xc0',
    '\xe3','\x4f','\xfc','\xc7','\x7f',
    '\xf1','\x4f','\xfc','\x07','\x00',
    '\xf1','\x4f','\xfc','\x07','\x00',
    '\xf9','\x4f','\xfc','\x03','\x00',
    '\xf9','\x47','\xfc','\x03','\x00',
    '\xf9','\x47','\xfc','\x03','\x00',
    '\xfc','\x47','\xfe','\xe3','\xff',
    '\xfc','\x47','\xfe','\xc1','\x07',
    '\xfc','\xc7','\xff','\x01','\x3c',
    '\xfc','\xc7','\xff','\xe1','\xff',
    '\xfc','\xc7','\xff','\x00','\x00',
    '\xfe','\xc7','\xff','\x00','\x00',
    '\xfe','\xc7','\x7f','\x00','\x00',
    '\xfe','\x87','\x3f','\x00','\x00',
    '\xfe','\x87','\x3f','\x04','\x00',
    '\xfe','\x07','\x1f','\x04','\x00',
    '\xfe','\x07','\x0e','\x04','\x00',
    '\xfe','\x07','\x00','\x04','\x00',
    '\xfc','\x07','\x00','\x02','\x00',
    '\xfc','\x07','\x00','\x02','\x00',
    '\xfc','\x07','\x00','\x02','\x00',
    '\xfc','\x07','\x00','\xe3','\xff',
    '\xf8','\x07','\x00','\x01','\x80',
    '\xf8','\x07','\x80','\x01','\x80',
    '\xf0','\x06','\x80','\x01','\x80',
    '\x60','\x0e','\xc0','\x00','\x00',
    '\x00','\x0e','\xc0','\x00','\x00',
    '\x00','\x0e','\x60','\x00','\x00',
    '\x00','\x0e','\x60','\x00','\xe0',
    '\x00','\x1e','\x70','\x00','\x3f',
    '\x00','\x1e','\x38','\xe0','\x21',
    '\x00','\x3e','\x3c','\x00','\x3f',
    '\x00','\x7e','\x1e','\x00','\xe0',
    '\x00','\xff','\x1f','\x00','\x00',
    '\x00','\xff','\x0f','\x00','\x00',
    '\x82','\xff','\x0f','\x00','\x00',
    '\xc6','\xff','\x07','\x00','\x00',
    '\xee','\xff','\x03','\xe0','\xff',
    '\xfc','\xff','\x01','\x20','\x84',
    '\xfc','\xff','\x00','\x20','\x84',
    '\xf8','\xff','\x00','\xc0','\x7b',
    '\xf0','\x7f','\x00','\x00','\x00',
    '\xe0','\x1f','\x00','\x00','\x00',
    '\xc0','\x0f','\x00','\x00','\x00',
    '\x0e','\x03','\x00','\xc0','\x61',
    '\x0e','\x00','\x00','\x60','\xc2',
    '\x0e','\x00','\x00','\x60','\xc4',
    '\x00','\x00','\x00','\xc0','\x78'
};


